# Generated by Django 5.0.6 on 2024-07-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image',
        ),
    ]
