# Generated by Django 5.0.6 on 2024-07-11 05:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_image1_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.FloatField()),
                ('image', models.ImageField(upload_to='order/image')),
                ('phone', models.CharField(max_length=12)),
                ('isPay', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 11, 11, 35, 49, 282541))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
