# Generated by Django 5.0.6 on 2024-07-11 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_address_alter_order_date_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 11, 12, 46, 33, 250831)),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
